import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { Tabbar, TabbarItem } from 'vant'
import { Card } from 'vant'
import { Tag } from 'vant'
import { Button } from 'vant'
import { NavBar } from 'vant'
import { ConfigProvider } from 'vant'
import { Col, Row } from 'vant'
import { ActionSheet } from 'vant'
import { TreeSelect } from 'vant'
import { Toast } from 'vant'
import { Icon } from 'vant'
import { createPinia } from 'pinia'
import { Circle } from 'vant'
import { Divider } from 'vant'
import { Step, Steps } from 'vant'
import { DropdownMenu, DropdownItem } from 'vant'
import { Tab, Tabs } from 'vant'
import { Switch } from 'vant'
import { Cell, CellGroup } from 'vant'
import { Sticky } from 'vant'
import { CountDown } from 'vant'
import { Search } from 'vant'
import { Popover } from 'vant'
import 'vant/es/toast/style'
import 'vant/lib/index.css'
import axios from 'axios'

axios.defaults.baseURL = ''

createApp(App).use(router).use(Tabbar).use(TabbarItem).use(Card).use(Tag).use(Button).use(NavBar).use(ConfigProvider).use(Col).use(Row).use(ActionSheet).use(TreeSelect).use(Toast).use(Icon).use(createPinia()).use(Circle).use(Divider).use(Step).use(Steps).use(DropdownItem).use(DropdownMenu).use(Tab).use(Tabs).use(Switch).use(Cell).use(CellGroup).use(Sticky).use(CountDown).use(Search).use(Popover).mount('#app')